from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox, QErrorMessage
from PyQt6.QtGui import QIcon

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(300, 330)
        MainWindow.setWindowIcon(QIcon("calc_ico.png"))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(176, 176, 176);\n""color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.pushButton1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(0, 50, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton1.setFont(font)
        self.pushButton1.setStyleSheet("background-color: rgb(158, 158, 158);\n""color: rgb(255, 255, 255);")
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(80, 50, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton2.setFont(font)
        self.pushButton2.setStyleSheet("background-color: rgb(158, 158, 158);\n""color: rgb(255, 255, 255);")
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton3.setGeometry(QtCore.QRect(160, 50, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton3.setFont(font)
        self.pushButton3.setStyleSheet("background-color: rgb(158, 158, 158);\n""color: rgb(255, 255, 255);")
        self.pushButton3.setObjectName("pushButton3")
        self.pushButtonPlus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPlus.setGeometry(QtCore.QRect(240, 50, 61, 71))
        self.pushButtonPlus.setStyleSheet("color: rgb(255, 255, 255);\n""background-color: rgb(255, 145, 11);")
        self.pushButtonPlus.setObjectName("pushButtonPlus")
        self.pushButton5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton5.setGeometry(QtCore.QRect(80, 120, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton5.setFont(font)
        self.pushButton5.setStyleSheet("background-color: rgb(158, 158, 158);\n""color: rgb(255, 255, 255);")
        self.pushButton5.setObjectName("pushButton5")
        self.pushButton4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton4.setGeometry(QtCore.QRect(0, 120, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton4.setFont(font)
        self.pushButton4.setStyleSheet("background-color: rgb(158, 158, 158);\n""color: rgb(255, 255, 255);")
        self.pushButton4.setObjectName("pushButton4")
        self.pushButton6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton6.setGeometry(QtCore.QRect(160, 120, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton6.setFont(font)
        self.pushButton6.setStyleSheet("background-color: rgb(158, 158, 158);\n""color: rgb(255, 255, 255);")
        self.pushButton6.setObjectName("pushButton6")
        self.pushButtonMinus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMinus.setGeometry(QtCore.QRect(240, 120, 61, 71))
        self.pushButtonMinus.setStyleSheet("color: rgb(255, 255, 255);\n""background-color: rgb(255, 145, 11);")
        self.pushButtonMinus.setObjectName("pushButtonMinus")
        self.pushButtonMultiply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMultiply.setGeometry(QtCore.QRect(240, 190, 61, 71))
        self.pushButtonMultiply.setStyleSheet("color: rgb(255, 255, 255);\n""background-color: rgb(255, 145, 11);")
        self.pushButtonMultiply.setObjectName("pushButtonMultiply")
        self.pushButton7 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton7.setGeometry(QtCore.QRect(0, 190, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton7.setFont(font)
        self.pushButton7.setStyleSheet("background-color: rgb(158, 158, 158);\n""color: rgb(255, 255, 255);")
        self.pushButton7.setObjectName("pushButton7")
        self.pushButton9 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton9.setGeometry(QtCore.QRect(160, 190, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton9.setFont(font)
        self.pushButton9.setStyleSheet("background-color: rgb(158, 158, 158);\n""color: rgb(255, 255, 255);")
        self.pushButton9.setObjectName("pushButton9")
        self.pushButton8 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton8.setGeometry(QtCore.QRect(80, 190, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton8.setFont(font)
        self.pushButton8.setStyleSheet("background-color: rgb(158, 158, 158);\n""color: rgb(255, 255, 255);")
        self.pushButton8.setObjectName("pushButton8")
        self.pushButtonComma = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonComma.setGeometry(QtCore.QRect(0, 260, 81, 71))
        self.pushButtonComma.setStyleSheet("background-color: rgb(158, 158, 158);\n""color: rgb(255, 255, 255);")
        self.pushButtonComma.setObjectName("pushButtonComma")
        self.pushButtonEqual = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonEqual.setGeometry(QtCore.QRect(160, 260, 81, 71))
        self.pushButtonEqual.setStyleSheet("color: rgb(255, 255, 255);\n""background-color: rgb(255, 145, 11);")
        self.pushButtonEqual.setObjectName("pushButtonEqual")
        self.pushButton0 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton0.setGeometry(QtCore.QRect(80, 260, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton0.setFont(font)
        self.pushButton0.setStyleSheet("background-color: rgb(158, 158, 158);\n""color: rgb(255, 255, 255);")
        self.pushButton0.setObjectName("pushButton0")
        self.pushButtonDevide = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDevide.setGeometry(QtCore.QRect(240, 259, 61, 71))
        self.pushButtonDevide.setStyleSheet("color: rgb(255, 255, 255);\n""background-color: rgb(255, 145, 11);")
        self.pushButtonDevide.setObjectName("pushButtonDevide")
        self.label.raise_()
        self.pushButton1.raise_()
        self.pushButton2.raise_()
        self.pushButton3.raise_()
        self.pushButtonPlus.raise_()
        self.pushButton4.raise_()
        self.pushButton7.raise_()
        self.pushButton5.raise_()
        self.pushButton6.raise_()
        self.pushButton8.raise_()
        self.pushButton9.raise_()
        self.pushButtonMinus.raise_()
        self.pushButtonMultiply.raise_()
        self.pushButtonComma.raise_()
        self.pushButton0.raise_()
        self.pushButtonEqual.raise_()
        self.pushButtonDevide.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_func()

        self.is_equal = False

    def add_func(self):
        self.pushButton0.clicked.connect(lambda: self.write(self.pushButton0.text()))
        self.pushButton1.clicked.connect(lambda: self.write(self.pushButton1.text()))
        self.pushButton2.clicked.connect(lambda: self.write(self.pushButton2.text()))
        self.pushButton3.clicked.connect(lambda: self.write(self.pushButton3.text()))
        self.pushButton4.clicked.connect(lambda: self.write(self.pushButton4.text()))
        self.pushButton5.clicked.connect(lambda: self.write(self.pushButton5.text()))
        self.pushButton6.clicked.connect(lambda: self.write(self.pushButton6.text()))
        self.pushButton7.clicked.connect(lambda: self.write(self.pushButton7.text()))
        self.pushButton8.clicked.connect(lambda: self.write(self.pushButton8.text()))
        self.pushButton9.clicked.connect(lambda: self.write(self.pushButton9.text()))
        self.pushButtonPlus.clicked.connect(lambda: self.write(self.pushButtonPlus.text()))
        self.pushButtonMinus.clicked.connect(lambda: self.write(self.pushButtonMinus.text()))
        self.pushButtonMultiply.clicked.connect(lambda: self.write(self.pushButtonMultiply.text()))
        self.pushButtonDevide.clicked.connect(lambda: self.write(self.pushButtonDevide.text()))
        self.pushButtonComma.clicked.connect(lambda: self.write(self.pushButtonComma.text()))

        self.pushButtonEqual.clicked.connect(self.result)

    def write(self,number):
        if self.label.text()=="0" or self.is_equal:
            self.label.setText(number)
        else:
            self.label.setText(self.label.text()+number)
        self.is_equal=False

    def result(self):
        if not self.is_equal:
            try:
                res = eval(self.label.text())
                self.label.setText(str(res))
                self.is_equal=True
            except:
                error = QMessageBox()
                error.setIcon(QMessageBox.Icon.Warning)
                error.setWindowTitle("Error")
                error.setText("At the moment this action can't be done!")
                error.setStandardButtons(QMessageBox.StandardButton.Reset|QMessageBox.StandardButton.Ok)
                error.setInformativeText("This action can't be done twice!")
                error.setDetailedText("Details...")
                error.exec()
                self.label.setText("")
        else:
            error = QMessageBox()
            error.setIcon(QMessageBox.Icon.Warning)
            error.setWindowTitle("Error")
            error.setText("At the moment this action can't be done!")
            error.setStandardButtons(QMessageBox.StandardButton.Ok)
            error.exec()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "0"))
        self.pushButton1.setText(_translate("MainWindow", "1"))
        self.pushButton2.setText(_translate("MainWindow", "2"))
        self.pushButton3.setText(_translate("MainWindow", "3"))
        self.pushButtonPlus.setText(_translate("MainWindow", "+"))
        self.pushButton5.setText(_translate("MainWindow", "5"))
        self.pushButton4.setText(_translate("MainWindow", "4"))
        self.pushButton6.setText(_translate("MainWindow", "6"))
        self.pushButtonMinus.setText(_translate("MainWindow", "-"))
        self.pushButtonMultiply.setText(_translate("MainWindow", "*"))
        self.pushButton7.setText(_translate("MainWindow", "7"))
        self.pushButton9.setText(_translate("MainWindow", "9"))
        self.pushButton8.setText(_translate("MainWindow", "8"))
        self.pushButtonComma.setText(_translate("MainWindow", "."))
        self.pushButtonEqual.setText(_translate("MainWindow", "="))
        self.pushButton0.setText(_translate("MainWindow", "0"))
        self.pushButtonDevide.setText(_translate("MainWindow", "/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
